INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /receipt_back/save_receipt
INFO:django.utils.autoreload:/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/api.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /receipt_back/save_receipt
Traceback (most recent call last):
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/api.py", line 77, in save_receipt
    save_trip.delay(user, img_path)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/celery/app/base.py", line 756, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type User is not JSON serializable
INFO:django.utils.autoreload:/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/tasks.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/tasks.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /receipt_back/current_data
Traceback (most recent call last):
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/api.py", line 27, in get_current_data
    overview, top_three = history.get_data_for_overview()
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 67, in get_data_for_overview
    trips = sorted(self.all_trips, key=lambda x: self.get_date(x.trip_date))
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 67, in <lambda>
    trips = sorted(self.all_trips, key=lambda x: self.get_date(x.trip_date))
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 28, in get_date
    d, m, y = date.day, date.month, date.year
AttributeError: 'NoneType' object has no attribute 'day'
ERROR:django.request:Internal Server Error: /receipt_back/current_data
Traceback (most recent call last):
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/receipt_back/api.py", line 27, in get_current_data
    overview, top_three = history.get_data_for_overview()
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 67, in get_data_for_overview
    trips = sorted(self.all_trips, key=lambda x: self.get_date(x.trip_date))
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 67, in <lambda>
    trips = sorted(self.all_trips, key=lambda x: self.get_date(x.trip_date))
  File "/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py", line 28, in get_date
    d, m, y = date.day, date.month, date.year
AttributeError: 'NoneType' object has no attribute 'day'
INFO:django.utils.autoreload:/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/gwyrwch/PycharmProjects/coursebattle/yourbudget/datahandling/ShoppingHistory.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
